version: '3'

volumes:
  kittygram_pg_data:
  kittygram_static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data

  backend:
    image: nikolala13/kittygram_backend
    env_file: .env
    volumes:
      - kittygram_static:/backend_static
      - media:/media/
    depends_on:
      - db

  frontend:
    image: nikolala13/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - kittygram_static:/frontend_static

  gateway:
    image: nikolala13/kittygram_gateway
    env_file: .env
    volumes:
      - kittygram_static:/static
      - media:/media/
    ports:
      - ${NGINX_PORT}:${HOST_PORT} 
    depends_on:
      - db